# Generated by Django 5.0.4 on 2024-05-04 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Phone',
            new_name='products',
        ),
    ]
